<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:template match="document">
        <!-- first make to TOC page -->
<xsl:document href="JmolScriptHelp" method="text"
>#acl AdminGroup:admin,read,write Known:read All:read

= Jmol Script Help =
<xsl:for-each select=".//jmolcmd">
<xsl:text>[:</xsl:text><xsl:value-of select="concat('Script', concat(translate(substring(translate(normalize-space(cmdname), ' ()', ''),1,1),'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ'), substring(translate(normalize-space(cmdname), ' ()', ''),2)))"/><xsl:text>:</xsl:text><xsl:value-of select="normalize-space(cmdname)"/><xsl:text>][[BR]]
</xsl:text>
</xsl:for-each>
 
[[Include(/Discussion, , 3)]]

----
This page is autogenerated from Bob Hanson's documentation on
http://www.stolaf.edu/people/hansonr/jmol/docs/. Comments are appreciated though, and can be placed below.
</xsl:document>
        <!-- now do the separate pages -->
        <xsl:apply-templates select="cmdlist"/>
    </xsl:template>

    <xsl:template match="cmdlist">
        <xsl:apply-templates select="jmolcmd"/>
    </xsl:template>

    <xsl:template match="jmolcmd">
        <xsl:variable name="commandName" select="translate(normalize-space(cmdname), ' ()', '')"/>
        <xsl:message>Processing: <xsl:value-of select="$commandName"/></xsl:message>
        <xsl:call-template name="outputCommand">
            <xsl:with-param name="commandName" select="$commandName"/>
        </xsl:call-template>
    </xsl:template>

    <xsl:template name="outputCommand">
        <xsl:param name="commandName"/>
<xsl:document href="{concat('Script', concat(translate(substring($commandName,1,1),'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ'), substring($commandName,2)))}" method="text"
>#acl AdminGroup:admin,read,write Known:read All:read
        
= <xsl:value-of select="normalize-space(cmdname)"/> =

<xsl:value-of select="cmddescription"/>

<xsl:apply-templates select="cmdexamples"/>
<xsl:apply-templates select="cmddefinitions"/>
<xsl:apply-templates select="cmdhtml"/>
<xsl:apply-templates select="cmdxref"/>

[[Include(/Discussion, , 3)]]

----
This page is autogenerated from Bob Hanson's documentation on
http://www.stolaf.edu/people/hansonr/jmol/docs/. Comments are appreciated though, and can be placed below.
</xsl:document>
    </xsl:template>        
    
    <xsl:template match="cmdexamples">
=== Examples ===
<xsl:for-each select="cmdexample">
<xsl:text> </xsl:text><xsl:value-of select="normalize-space(cmdoption)"/>:: <xsl:value-of select="cmdlistidescription"/>
</xsl:for-each>

    </xsl:template>
						
    <xsl:template match="cmddefinitions">
=== Definitions ===
<xsl:for-each select="cmddef">
<xsl:text> </xsl:text><xsl:value-of select="normalize-space(defkey)"/>:: <xsl:value-of select="defdata"/><xsl:text>
</xsl:text>
</xsl:for-each>

    </xsl:template>

    <xsl:template match="cmdhtml">
=== Live Examples ===
<xsl:for-each select="a">
[http://www.stolaf.edu/people/hansonr/jmol/docs/<xsl:value-of select="@href"/><xsl:text> </xsl:text><xsl:value-of select="."/>]
</xsl:for-each>

    </xsl:template>

    <xsl:template match="cmdxref">
=== See Also ===
<xsl:for-each select="seealso">
<xsl:text>[:</xsl:text><xsl:value-of select="concat('Script', concat(translate(substring(translate(normalize-space(a), ' ()', ''),1,1),'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ'), substring(translate(normalize-space(a), ' ()', ''),2)))"/><xsl:text>:</xsl:text><xsl:value-of select="normalize-space(a)"/><xsl:text>] </xsl:text>
</xsl:for-each>

    </xsl:template>

</xsl:stylesheet>


