#!/bin/sh

# Collect -D options as java arguments
command=java
while [ `echo $1 | egrep '^-D' | wc -l` != 0 ]; do
	command="$command $1"
	shift
done

if [ -f ./jmol.jar ] ; then
  jarpath=./jmol.jar
elif [ -f $JMOL_HOME/jmol.jar ] ; then
  jarpath=$JMOL_HOME/jmol.jar
elif [ -f /usr/share/jmol/jmol.jar ] ; then
  jarpath=/usr/share/jmol/jmol.jar
else
  echo jmol.jar not found
  exit
fi
$command -jar $jarpath $@

