newDef('._poly_distance','(decimal)','maximum-distance','is in Angstroms')
newDef('._connection_options','SINGLE,DOUBLE,TRIPLE,QUADRUPLE, AROMATIC, PARTIAL, PARTIALDOUBLE, PARTIALTRIPLE, PARTIALTRIPLE2, PARTIAL N.M, UNSPECIFIED, or HBOND','connection-options','is')
newDef('._conn_mindist','(decimal)','minimum-distance','is in Angstroms')
newDef('._conn_maxdist','(decimal)','maximum-distance','is in Angstroms')
newDef('._viewing_distance','(integer),(decimal)','viewing-distance','the apparent distance from the model to the user in arbitrary units')
newDef('._anim_fps','(integer)','frames-per-second','the animation rate')


newDef('._atom_expression','','atom-expression','any {#.atom expressions~expression} that evaluates to a set of atoms')
newDef('._distance_unit','ANGSTROMS, AU, BOHR, NM, NANOMETERS,PM, or PICOMETERS','distance-unit','is')
newDef('._atomno','(integer, >=1)','atom-number','the sequential number assigned to the atom')
newDef('._axes_type','ON,OFF,DOTTED,._diameter_pixels,._axes_radius_angstroms','line-width-or-type','a line width or type for a drawing object')
newDef('._axes_radius_angstroms','(decimal, <2.0)','radius-in-angstroms','a scaling factor')
newDef('._color_identifier','.identifier','color-identifier','a color identifier')
newDef('._color_none','NONE','none','just "none", indicating the default value')
newDef('._colorRGB','(color name), [r,g,b],[xRRGGBB]','RGB-color','a name of a color or a red, green, blue color triple in decimal with commas, for example [255,0,255], or as a single hexadecimal number, for example [xFF00FF] (brackets included)')
newDef('._color_or_none','(color name), [r,g,b],[xRRGGBB],NONE','color-none-CPK','is')
newDef('._color_or_none_or_CPK','(color name), [r,g,b],[xRRGGBB],CPK,NONE','color-none-CPK','is')
newDef('._color_name_or_scheme','(color name), [r,g,b],[xRRGGBB],ALTLOC,AMINO,CHAIN,CPK,FIXEDTEMPERATURE,FORMALCHARGE,GROUP,INSERTION,JMOL,MOLECULE,MONOMER,NONE,PARTIALCHARGE,RASMOL,RELATIVETEMPERATURE,SHAPELY,STRUCTURE,SURFACEDISTANCE','color-scheme','to color based on a {http://jmol.sourceforge.net/jscolors/~[Jmol color scheme]}. (CPK and NONE are synonymous here)')
newDef('._element_name','(element name)','element-name','to color specific elements such as CARBON or HYDROGEN')
newDef('._atom_object','ATOM,BACKBONE,CARTOON,DOTS,ELLIPSOID,HALOS, LABELS,MESHRIBBON,POLYHEDRA,RIBBONS,ROCKETS, SELECTIONHALOS, STARS,STRANDS,STRUTS,TRACE,VECTORS','atom-associated-object','an object related to an atom')
newDef('._degrees','(integer)','number-of-degrees','the number of degrees')
newDef('._diameter_pixels','(integer, 1 to 19)','diameter-pixels','a scaling factor')
newDef('._dots_param','(integer, 0 to 1000)','dots-parameter','???')
newDef('._draw_object','$name','drawn-object','a drawn object')
newDef('._drotx','(integer)','x-rotation','the degrees of rotation about x')
newDef('._droty','(integer)','y-rotation','the degrees of rotation about y')
newDef('._drotz','(integer)','z-rotation','the degrees of rotation about z')
newDef('._dSlab','(integer)','slab-cutoff','the cutoff for the slab display')
newDef('._dtransx','(integer)','x-translation','the distance offset along x')
newDef('._dtransy','(integer)','y-translation','the distance offset along y')
newDef('._dtransz','(integer)','z-translation','the distance offset along z')
newDef('._dzoom','(integer)','zoom-factor','a scaling factor')
newDef('._echo_string','(string)','echo-string','???')
newDef('._floatSecondsTotal','(decimal)','seconds-total','the amount of time to wait')
newDef('._fontstyle','PLAIN, BOLD, ITALIC, or BOLDITALIC','font-style','is')
newDef('._fontface','SERIF, SANSSERIF, or MONOSPACED ','font-face','is')
newDef('._fontsize','(integer, JmolConstants.LABEL_MINIMUM_FONTSIZE to JmolConstants.LABEL_MAXIMUM_FONTSIZE)','font-size','approximately the same as Rasmol')
newDef('._mouse_action','any double-quoted combination of a control code (CTRL, ALT, or SHIFT) with a mouse button (LEFT, MIDDLE, RIGHT, or WHEEL) and a click type (SINGLE or DOUBLE)','mouse-action','is')
newDef('._jmol_action','_clickFrank,  _depth,  _dragDrawObject,  _dragDrawPoint,  _dragLabel,  _dragSelected,  _navTranslate,  _pickAtom,  _pickIsosurface,  _pickLabel,  _pickMeasure,  _pickNavigate,  _pickPoint,  _popupMenu,  _reset,  _rotate,  _rotateSelected,  _rotateZ,  _rotateZorZoom,  _select,  _selectAndNot,  _selectNone,  _selectOr,  _selectToggle,  _selectToggleOr,  _setMeasure,  _slab,  _slabAndDepth,  _slideZoom,  _spinDrawObjectCCW,  _spinDrawObjectCW,  _swipe,  _translate,  or _wheelZoom','jmol-action','is one of ')

newDef('._hbond_type','(string)','"TYPE','to indicate that the hydrogen bonds should be colored based on their type (proteins only)')
newDef('._hbond_width_angstroms','(decimal, <2.0)','width-in-angstroms','a')
newDef('._hbond_width_rasmol','(integer, <500)','width-by-Rasmol','in 1/250ths of an Angstrom (deprecated)')
newDef('._ignored_filetype','(string)','param-ignored','for Rasmol/chime compatibility; ignored')
newDef('._model_filename','(string)','file name','a model filename or URL')
newDef('._move_fps','(integer)','move-frames-per-second','the frames per second to move')
newDef('._move_maxAccel','(integer)','maximum-acceleration','the maximum acceleration')
newDef('._nbonds','(integer)','number_of_bonds','an')
newDef('._on_off','','"ON/OFF','')
newDef('._true_false','','TRUE/FALSE','')
newDef('._on_off_string','','"ON/OFF/string','')
newDef('._percent_ambient','(integer, 0 to 100)','ambient-percent','an')
newDef('._percent_diffuse','(integer, 0 to 100)','diffuse-percent','an')
newDef('._percent_slab','(integer, 0 to 100)','slab-percent','an')
newDef('._percent_specular','(integer, 0 to 100)','specular-percent','an')
newDef('._percent_translate','(integer, -100 to 100)','percent-translation','an')
newDef('._percent_zoom','(integer, 5 to 200000)','percent-zoom','an')
newDef('._probe_radius','(decimal)','probe-radius-in-angstroms','a')
newDef('._probe_radius_rasmol','(integer, <500)','probe-radius-Rasmol','in 1/250ths of an Angstrom (deprecated)')
newDef('._property_name','.identifier','property-name','an')
newDef('._echo_vertical','TOP,MIDDLE,BOTTOM','vertical-position','one of the following:')
newDef('._echo_horizontal','LEFT,CENTER,RIGHT','horizontal-position','one of the following:')
newDef('._radius_angstroms','(decimal, <=3.0)','radius-in-angstroms','a')
newDef('._radius_percent_vdw','(integer, -100 to -1)','radius-percent-vdw','as a percent of the van der Waals radius')
newDef('._radius_rasmol','(integer, 1 to 749)','radius-Rasmol','in 1/250ths of an Angstrom (deprecated)')
newDef('._script_filename','(string)','file-name','any valid filename or URL')
newDef('._select_all','(string)','"ALL','all atoms (not hydrogens or heteros if they are turned off')
newDef('._model_object','AXIS1*, AXIS2*, AXIS3*, AXES,BOUNDBOX,DRAW,ECHO,GEOSURFACE,HOVER,ISOSURFACE,LABEL,MEASUREMENTS,MO,PMESH,POLYHEDRA,SELECTIONHALOS,UNITCELL (*starting with Jmol 11.1.20)','model-object','is')
newDef('._object_with_background','HOVER,LABEL','object-with-background','is')
newDef('._object_with_text','AXES,ECHO,HOVER, LABEL, or MEASURE','object-with-text','is')
newDef('._rasmol_structure','BACKBONE,CARTOON,MESHRIBBON,RIBBON,ROCKET,STRANDS, or TRACE','Rasmol-structure','is')

newDef('._specular_power','(integer)','specular-power','an')
newDef('._spin_fps','(integer)','frames-per-second','an')
newDef('._spin_rate','(integer)','degrees-per-second','an')
newDef('._ssbond_width_angstroms','(decimal, <2.0)','width-angstroms','a')
newDef('._ssbond_width_rasmol','(integer, <500)','width-Rasmol','in 1/250ths of an Angstrom (deprecated)')
newDef('._ribbon_radius','(decimal, <=4.0)','ribbon-radius','half of the overall width of the ribbon')
newDef('._rocket_radius','(decimal, <=4.0)','rocket-radius','half of the overall width of the rocket barrel')
newDef('._stereo_angle','(integer|decimal)','stereo-viewing-angle','angle of rotation for stereo viewing')
newDef('._strand_count','(integer, 0 to 20)','strand-count','the number of strands')
newDef('._strand_radius','(decimal, <=4.0)','strand-radius','half of the overall width of the set of strands')
newDef('._time_delay','(integer|decimal, >=0)','time-delay','in seconds')
newDef('._time_delay1','(integer|decimal, >=0)','time-delay1','the time in seconds to pause on the first frame')
newDef('._time_delay2','(integer|decimal, >=0)','time-delay2','the time in seconds to pause on the last frame')
newDef('._anim_ignored','','param-ignored','ignored')
newDef('._variablename','(string)','variable-name','a')
newDef('._vector_scale','(decimal, -10.0 to 10.0)','vector-scale','a')
newDef('._vibration_scale','(decimal, -10.0 to 10.0)','vibration-scale','a')
newDef('._xoffset','(integer)','x-offset','the x-offset')
newDef('._xyz','.x,.y,.z','"X/Y/Z','')
newDef('._xyzminus','x, y, z, -x, -y, -z','"X/Y/Z/-X/-Y/-Z','')
newDef('._yoffset','(integer)','y-offset','the y-offset')
newDef('._backbone_radius','(decimal, <=4.0)','backbone-radius','the radius of the backbone')
newDef('._trace_radius','(decimal, <=4.0)','trace-radius','the radius of the trace')
newDef('._mesh_ribbon_radius','(decimal, <=4.0)','mesh-ribbon-radius','the overall radius of the mesh ribbon')
newDef('._cartoon_radius','(decimal, <=4.0)','cartoon-radius','the radius of the cartoon elements')
newDef('._color_temp_mode','FIXEDTEMPERATURE or RELATIVETEMPERATURE','temperature-mode','is')
newDef('._coordinate','(decimal)','coord-value','a')
newDef('._coordxyz','','xyz-coordinate','is an xyz coordinate in the form {{x y z}}')
newDef('._cwrotation','(decimal)','cw-rotation-deg','a')
newDef('._inttime','(seconds)','time-in-seconds','in')
newDef('._width_pixels','(integer)','linewidth-pixels','an')
newDef('._width_angstroms','(decimal, <2.0)','width-in-angstroms','a')
newDef('._time_period','(positive number)','time-period','number of seconds per vibration')
newDef('._length_angstroms','(decimal)','length-in-angstroms','')
newDef('._cutoff','(decimal)','cutoff-value','a')
newDef('._floattime','(seconds)','time-in-seconds','in')
newDef('._special_radius','STRUCTURE, TEMPERATURE, DISPLACEMENT','variable-radius','is')
newDef('._atom_expression_or_coord','','atom-expression-or-coordinate','is any {#.atom expressions~expression} surrounded by parentheses or braces, or any {{x y z}} coordinate')
newDef('._vdw_mode','JMOL, BABEL, RASMOL, USER','vdw-mode','is')
newDef('','','','')
newDef('','','','')
newDef('','','','')

JmolConstants=new Array()
JmolConstants.DEFAULT_FONTFACE = "SansSerif"
JmolConstants.DEFAULT_FONTSTYLE = "Plain"

JmolConstants.LABEL_MINIMUM_FONTSIZE =6
JmolConstants.LABEL_MAXIMUM_FONTSIZE =63
JmolConstants.LABEL_DEFAULT_FONTSIZE =13
JmolConstants.LABEL_DEFAULT_X_OFFSET =4
JmolConstants.LABEL_DEFAULT_Y_OFFSET =4

JmolConstants.MEASURE_DEFAULT_FONTSIZE =15
JmolConstants.AXES_DEFAULT_FONTSIZE =14
